spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
  properties.hibernate.search.default:
    directory_provider: filesystem
    indexBase: ${user.dir}/var/index/default

logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE